In [1]:
import numpy as np

# array of vector type
mylist=[1,2,3,4]  # two type of array in numpy 1.vector(1D) 2.matrix(2D)
print(type(mylist))
print(np.array(mylist)) # Convert 1D list into 1D ndarray 
myarr=np.array(mylist)
print(type(myarr))

<class 'list'>
[1 2 3 4]
<class 'numpy.ndarray'>

In [ ]:
# matrix array
my_matrix=[[1,2,3],[4,5,6],[7,8,9]]
print(my_matrix[2][1])
print(type(my_matrix))
mymatrix=np.array(my_matrix) # Convert a 2D List into 2D ndarray
print(type(mymatrix))
print(mymatrix)
print(mymatrix[2][1])
print(mymatrix[2,1])

8
<class 'list'>
<class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]]
8
8

In [ ]:
# built-in fn of numpy
# ===========================np.arange()==========================

# Print counting no from 0 to 9.
print(np.arange(0,10)) # 1D array,excluding 10

# print counting no from 0 to 100 with a gap of 10.
print(np.arange(0,101,10)) # 1D array with gap between elements is 10

[0 1 2 3 4 5 6 7 8 9]
[  0  10  20  30  40  50  60  70  80  90 100]

In [ ]:
# np.zeros
arr_zero=np.zeros(5)  # it makes a ndarray of float type of all values zero
print(arr_zero)
print(type(arr_zero))
mat_zero=np.zeros((3,4)) # it creates a matrix of float with all values zero
print(mat_zero)

[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

In [ ]:
# np.ones
mat_one=np.ones((3,4))# it creat matrix of float type and one as its entity
print(mat_one)

# np.linspace
print(np.linspace(0,10,4)) # 0 start, 10 end and 4 means 4 element in the array 
# with (end-start) equally divided into 4 parts

# np.eye()  ->  to create identity matrix which is a square matrix too
print(np.eye(3))

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[ 0.          3.33333333  6.66666667 10.        ]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

In [ ]:
print(np.random.rand(3)) # random.rand gives a floating no form [0 ,1] in array
print(np.random.rand(3,2))
print(np.random.randint(1,50,5)) # return 5 random no b/w 1 to 50
np.random.seed(40) # it creates a set of random ,each time same random no.
# anywhere if we use these seed with same value get the same set of random no.
print(np.random.rand(4))

[0.73814404 0.19352079 0.08502326]
[[0.70989731 0.42420473]
 [0.80572277 0.9377868 ]
 [0.34259769 0.61774299]]
[16 31 41 41 44]
[0.40768703 0.05536604 0.78853488 0.28730518]

In [ ]:
# we can reshape a matrix with new have same entity as that of previous one.
arr=np.arange(1,101,10)
print(arr)
np.random.seed(43)
arr=np.random.randint(1,100,10)
print(arr.reshape(2,5))
print(arr.shape)
print(arr.max(),arr.min()) # min() and max() returns the min max value of arr
print(arr.argmax(),arr.argmin()) # return index of min max elements
print(arr.shape)
print(arr.reshape(5,2).shape)

[ 1 11 21 31 41 51 61 71 81 91]
[[69 65 50 22 59]
 [17 52 18 60 92]]
(10,)
92 17
9 5
(10,)
(5, 2)